### ISSUE TITLE
Sometimes the Atlantis enabled state is set to "Off" when leaving the Atlantis Settings Activity

### ISSUE THREAD

**Issue by echsylon** [echsylon/atlantis-extra#1]

**Comment by laszlourszuly** [comment]
This seems to be caused by the `AtlantisService` unexpectedly being destroyed.

**Steps to reproduce:**
1. Ensure log output is observeable (e.g. `adb -e logcat | grep ATLANTIS` in the terminal).
1. Start the Atlantis Settings Activity.
1. Enable Atlantis if not enabled.
1. Then rather quickly (but not necessarily super quickly) disable Atlantis and enabled it again and "back" out of the Activity.

**Expected behavior:**
* Watching the log prints one should see `Ready for connections` as the last output.
* Reaching out for a configured `localhost:8080` endpoint returns the mocked content.

**Actual behavior:**
* The last log print says `Successfully shut down`.
* Reaching out for a configured `localhost:8080` endpoint results in an exception.
